# To hide a menu item, add an 'x' inside the brackets, like [x]
# To show a menu item, leave the brackets empty, like [ ]

# -- LEGO SYSTEM LAUNCHER --
[ ] Lego Management System
[ ] Lego Lookup
[x] View License
[x] Settings

# -- Lego Management System Menu --
[ ] Personal Collection
[x] Non Retired Lego Sets
[x] Retired Lego Sets

# -- Personal Collection Menu --
[ ] Manage Lego Parts
[ ] Manage Lego Sets

# -- Lego Lookup Menu --
[ ] Lookup by Set
[ ] Lookup by Part
