# To hide a menu item, add an 'x' inside the brackets, like [x]
# To show a menu item, leave the brackets empty, like [ ]

# -- LEGO SYSTEM LAUNCHER --
[ ] Lego Management System
[ ] Lego Lookup
[ ] View License
[x] Settings # Need to Remove

# -- Lego Management System Menu --
[ ] Personal Collection
[ ] Non Retired Lego Sets
[ ] Retired Lego Sets

# -- Personal Collection Menu --
[ ] Manage Lego Parts
[ ] Manage Lego Sets

# -- Lego Lookup Menu --
[ ] Lookup by Set
[ ] Lookup by Part
